#!/usr/bin/env bash
# VIPOS Cron Job Setup Script
#
# This script sets up automated tasks:
# 1. Daily database backup (02:00 UTC)
# 2. Weekly backup verification (Sunday 03:00 UTC)
# 3. Monthly backup cleanup (1st day 04:00 UTC)
#
# USAGE:
#   sudo ./scripts/setup-cron.sh
#
# REQUIREMENTS:
#   - Run as root or with sudo
#   - VIPOS installed in /var/www/vipos

set -euo pipefail

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log() {
    echo -e "${GREEN}[$(date -u +%FT%TZ)]${NC} $*"
}

error() {
    echo -e "${RED}[$(date -u +%FT%TZ)] ERROR:${NC} $*" >&2
}

warn() {
    echo -e "${YELLOW}[$(date -u +%FT%TZ)] WARN:${NC} $*"
}

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root or with sudo"
    exit 1
fi

log "=== VIPOS Cron Job Setup ==="

# ---------- Configuration ----------
VIPOS_DIR="${VIPOS_DIR:-/var/www/vipos}"
BACKUP_DIR="${BACKUP_DIR:-/var/backups/vipos}"
LOG_DIR="${LOG_DIR:-/var/log/vipos}"
CRON_USER="${CRON_USER:-root}"

log "VIPOS directory: $VIPOS_DIR"
log "Backup directory: $BACKUP_DIR"
log "Log directory: $LOG_DIR"
log "Cron user: $CRON_USER"

# Verify VIPOS directory exists
if [[ ! -d "$VIPOS_DIR" ]]; then
    error "VIPOS directory not found: $VIPOS_DIR"
    exit 1
fi

# Create directories
mkdir -p "$BACKUP_DIR"
mkdir -p "$LOG_DIR"

# Set permissions
chown -R "$CRON_USER:$CRON_USER" "$BACKUP_DIR"
chown -R "$CRON_USER:$CRON_USER" "$LOG_DIR"
chmod 755 "$BACKUP_DIR"
chmod 755 "$LOG_DIR"

log "Directories created and permissions set"

# ---------- Create Cron Jobs ----------
CRON_FILE="/etc/cron.d/vipos-backup"

log "Creating cron configuration: $CRON_FILE"

cat > "$CRON_FILE" <<'EOF'
# VIPOS Automated Backup & Maintenance Tasks
# Generated by setup-cron.sh
#
# Format: minute hour day month weekday user command

SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
VIPOS_DIR=/var/www/vipos
BACKUP_DIR=/var/backups/vipos
LOG_DIR=/var/log/vipos

# Daily backup at 02:00 UTC
0 2 * * * root cd $VIPOS_DIR && bash apps/backend/scripts/backup-production.sh >> $LOG_DIR/backup.log 2>&1

# Weekly backup verification (Sunday at 03:00 UTC)
0 3 * * 0 root cd $VIPOS_DIR && bash apps/backend/scripts/verify-backup.sh >> $LOG_DIR/backup-verify.log 2>&1

# Monthly log rotation (1st day of month at 04:00 UTC)
0 4 1 * * root find $LOG_DIR -name "*.log" -type f -mtime +30 -delete

# Daily health check log (every 6 hours)
0 */6 * * * root curl -fsS http://localhost:3001/health/detailed > $LOG_DIR/health-$(date +\%Y\%m\%d-\%H\%M).json 2>&1 || echo "Health check failed" >> $LOG_DIR/health-error.log

# Disk space alert (daily at 08:00 UTC)
0 8 * * * root df -h | grep -E '^/dev/' | awk '{if ($5+0 > 80) print "WARNING: Disk usage on " $1 " is " $5}' >> $LOG_DIR/disk-alert.log 2>&1

EOF

# Set proper permissions for cron file
chmod 644 "$CRON_FILE"
chown root:root "$CRON_FILE"

log "Cron configuration created"

# ---------- Make Scripts Executable ----------
log "Making backup scripts executable..."

chmod +x "$VIPOS_DIR/apps/backend/scripts/backup-production.sh"
chmod +x "$VIPOS_DIR/apps/backend/scripts/restore-production.sh"
chmod +x "$VIPOS_DIR/apps/backend/scripts/verify-backup.sh"

log "Scripts are now executable"

# ---------- Test Backup Script ----------
log "Testing backup script..."

if bash "$VIPOS_DIR/apps/backend/scripts/backup-production.sh"; then
    log "✓ Backup script test: SUCCESS"
else
    error "✗ Backup script test: FAILED"
    warn "Please check the script and try again"
fi

# ---------- Setup Logrotate ----------
log "Setting up log rotation..."

LOGROTATE_FILE="/etc/logrotate.d/vipos"

cat > "$LOGROTATE_FILE" <<'EOF'
/var/log/vipos/*.log {
    daily
    rotate 30
    compress
    delaycompress
    notifempty
    missingok
    create 0644 root root
    sharedscripts
    postrotate
        # Reload PM2 logs if needed
        pm2 reloadLogs > /dev/null 2>&1 || true
    endscript
}
EOF

chmod 644 "$LOGROTATE_FILE"
log "Logrotate configuration created"

# ---------- Setup Healthcheck Monitoring (Optional) ----------
if command -v curl >/dev/null 2>&1; then
    log "Setting up healthcheck monitoring..."
    
    # Test health endpoint
    if curl -fsS http://localhost:3001/health >/dev/null 2>&1; then
        log "✓ Health endpoint is accessible"
    else
        warn "Health endpoint not accessible (server may not be running)"
    fi
fi

# ---------- Summary ----------
log ""
log "=== Setup Complete ==="
log ""
log "Cron jobs configured:"
log "  - Daily backup: 02:00 UTC"
log "  - Weekly verification: Sunday 03:00 UTC"
log "  - Monthly cleanup: 1st day 04:00 UTC"
log "  - Health checks: Every 6 hours"
log "  - Disk alerts: Daily 08:00 UTC"
log ""
log "Log files:"
log "  - Backup logs: $LOG_DIR/backup.log"
log "  - Verification logs: $LOG_DIR/backup-verify.log"
log "  - Health checks: $LOG_DIR/health-*.json"
log "  - Disk alerts: $LOG_DIR/disk-alert.log"
log ""
log "Manual commands:"
log "  - Run backup now: sudo bash $VIPOS_DIR/apps/backend/scripts/backup-production.sh"
log "  - Verify backup: sudo bash $VIPOS_DIR/apps/backend/scripts/verify-backup.sh"
log "  - View cron jobs: sudo crontab -l -u $CRON_USER"
log "  - Check logs: tail -f $LOG_DIR/backup.log"
log ""
log "Next steps:"
log "  1. Configure S3_BUCKET in .env for remote backup"
log "  2. Test restore process: bash $VIPOS_DIR/apps/backend/scripts/restore-production.sh --help"
log "  3. Setup monitoring alerts (email/SMS on backup failure)"
log ""
log "✓ Cron setup complete!"

exit 0
